<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="math" nsURI="http://math" nsPrefix="math">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Division">
    <eStructuralFeatures xsi:type="ecore:EReference" name="numerator" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="denominator" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sqrt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="radicand" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Power" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exponent" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modulo" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factorial" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Absolute" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sum" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Integral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="func" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parenthesized" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixExpr" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//MatrixContent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="2" eType="#//MatrixRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="2"
        eType="#//Expression"/>
  </eClassifiers>
</ecore:EPackage>
